#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.1                         #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -std=c++17 -fexceptions
RESINC = 
LIBDIR = 
LIB = -lgmp -lz -lsoplex -lpthread
LDFLAGS = 

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/pwl2limodsat

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/Formula.o $(OBJDIR_RELEASE)/src/InputParser.o $(OBJDIR_RELEASE)/src/LinearPiece.o $(OBJDIR_RELEASE)/src/PiecewiseLinearFunction.o $(OBJDIR_RELEASE)/src/RegionalLinearPiece.o $(OBJDIR_RELEASE)/src/VariableManager.o

all: release

clean: clean_release

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/Formula.o: src/Formula.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Formula.cpp -o $(OBJDIR_RELEASE)/src/Formula.o

$(OBJDIR_RELEASE)/src/InputParser.o: src/InputParser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/InputParser.cpp -o $(OBJDIR_RELEASE)/src/InputParser.o

$(OBJDIR_RELEASE)/src/LinearPiece.o: src/LinearPiece.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/LinearPiece.cpp -o $(OBJDIR_RELEASE)/src/LinearPiece.o

$(OBJDIR_RELEASE)/src/PiecewiseLinearFunction.o: src/PiecewiseLinearFunction.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/PiecewiseLinearFunction.cpp -o $(OBJDIR_RELEASE)/src/PiecewiseLinearFunction.o

$(OBJDIR_RELEASE)/src/RegionalLinearPiece.o: src/RegionalLinearPiece.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/RegionalLinearPiece.cpp -o $(OBJDIR_RELEASE)/src/RegionalLinearPiece.o

$(OBJDIR_RELEASE)/src/VariableManager.o: src/VariableManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/VariableManager.cpp -o $(OBJDIR_RELEASE)/src/VariableManager.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_release after_release clean_release

